# Copyright 2024 Silicon Laboratories Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: silabs
      url-base: https://github.com/siliconlabssoftware

  projects:
    - name: zephyr-mbedtls
      remote: silabs
      revision: 43bb1e577e2accfaa135464bac181ed2a0cc0489
      path: modules/crypto/mbedtls
    - name: zephyr-mcuboot
      remote: silabs
      revision: 30a3475547e6c557d019943ef652af2e249d7883
      path: bootloader/mcuboot
    - name: zephyr
      remote: silabs
      revision: 3568e1b6d5cdd51a6b964a2a1d6d29200fea2056
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis_6    # required by the ARM port
          - hal_silabs # required by Silabs boards
