# Copyright 2024 Silicon Laboratories Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: silabs
      url-base: https://github.com/siliconlabssoftware

  projects:
    - name: hal_silabs
      remote: silabs
      revision: d3191b380c5a0975230881bcf21045e92189c263
      path: modules/hal/silabs
    - name: zephyr
      remote: zephyrproject-rtos
      revision: ba62c8d87641d025d268763c176e9b90b9008ce6
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_silabs # required by Silabs boards
          - mbedtls    # required e.g. by Bluetooth
          - tinycrypt  # required e.g. by Bluetooth
