# Copyright 2024 Silicon Laboratories Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: silabs
      url-base: https://github.com/siliconlabssoftware

  projects:
    - name: hal_silabs
      remote: silabs
      revision: edc0c9b40b70170807ba153550b1286a5a04f30f
      path: modules/hal/silabs
    - name: zephyr-mbedtls
      remote: silabs
      revision: 6024c415bf050c09e3990bddb6d53d3b4990a2b1
      path: modules/crypto/mbedtls
    - name: zephyr
      remote: zephyrproject-rtos
      revision: 222f8d87b546c5e91ce132449b4fd41d55ed7207
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis      # required by the ARM port
          - hal_silabs # required by Silabs boards
          - tinycrypt  # required e.g. by Bluetooth
