# Copyright 2024 Silicon Laboratories Inc.
# SPDX-License-Identifier: Apache-2.0

# West manifest file for Simplicity SDK for Zephyr.
#
# The west workspace configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom workspaces.
# For example, you could create a manifest file in your own application
# directory, which would pull this repository in as an ordinary project.
#
# You can pass your manifest repository to west init when creating a
# new workspace. See the west documentation for more information.

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: silabs
      url-base: https://github.com/siliconlabssoftware

  projects:
    - name: zephyr
      remote: silabs
      revision: f700b5c57ca27a95634947809194aaab5b7511e8
      import:
        # Simplicity SDK for Zephyr imports the Zephyr main tree at the
        # revision given above. Only the modules named below are imported.
        # If a module is overridden it is not listed here, and instead
        # added separately at the top level.
        name-allowlist:
          - cmsis-dsp
          - cmsis-nn
          - cmsis_6
          - fatfs
          - hal_silabs
          - littlefs
          - lvgl
          - picolibc
          - segger
          - zcbor
    - name: mbedtls
      remote: silabs
      repo-path: zephyr-mbedtls
      revision: bb997b915d08a8a1ae45966df44a5ae32f308793
      path: modules/crypto/mbedtls
    - name: mcuboot
      remote: silabs
      repo-path: zephyr-mcuboot
      revision: 30a3475547e6c557d019943ef652af2e249d7883
      path: bootloader/mcuboot
    - name: zephyr-hal-silabs-extra
      remote: silabs
      revision: 04ea2a26baf2d0a768ce5c8970a754bbdd71e9b1
      path: modules/hal/silabs_extra
