name: Silabs upstream daily build

on:
  schedule:
    - cron: "15 5 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-silabs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Update manifest to point at upstream main branch
        working-directory: zephyr-silabs
        shell: bash
        run: |
          yq -i '(.manifest.projects[] | select(.name == "zephyr") | .revision) = "main"' west.yml

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-silabs
          toolchains: arm-zephyr-eabi

      - name: Fetch blobs
        shell: bash
        run: |
          west blobs fetch hal_silabs

      - name: Build Entropy test
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -s drivers.entropy \
            -p siwx917_rb4338a

      - name: Build Flash test
        shell: bash
        run: |
          west twister -v --inline-logs \
            -s drivers.flash.common.default \
            -p siwx917_rb4338a

      - name: Build DMA test
        shell: bash
        run: |
          west twister -v --inline-logs \
            -s drivers.dma.chan_blen_transfer \
            -p siwx917_rb4338a

      - name: Build Bluetooth samples
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -s sample.bluetooth.peripheral_hr \
            -s sample.bluetooth.observer \
            -p xg27_dk2602a \
            -p siwx917_rb4338a

      - name: Build Wifi samples
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -s sample.net.wifi \
            -p siwx917_rb4338a
          west twister -v --inline-logs -K \
            -s sample.net.wifi.siwx91x_offloaded \
            -p siwx917_rb4338a

      - name: Build Rail samples
        shell: bash
        run: |
          west twister -v --inline-logs \
            -s sample.rail.simple_txrx -T zephyr-silabs/samples
