name: Silabs upstream daily build

on:
  schedule:
    - cron: "15 5 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-silabs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Silabs-specific python dependencies
        run: |
          pip3 install crc

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-silabs
          toolchains: arm-zephyr-eabi

      - name: Update manifest to point at upstream main branch
        working-directory: zephyr-silabs
        shell: bash
        run: |
          Z_REV=`west list zephyr -f {revision}`
          sed s/$Z_REV/main/ west.yml > west.yml.new
          mv west.yml.new west.yml
          west update

      - name: Fetch blobs
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west blobs fetch hal_silabs

      - name: Build Entropy test
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s drivers.entropy -p siwx917_rb4338a -v --inline-logs -K

      - name: Build Flash test
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s drivers.flash.common.default -p siwx917_rb4338a -x DTC_OVERLAY_FILE=$(pwd)/tests/drivers/flash/common/boards/siwx917_rb4338a.overlay -v --inline-logs

      - name: Build Bluetooth samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -p xg27_dk2602a \
            -p siwx917_rb4338a \
            -s sample.bluetooth.peripheral_hr \
            -s sample.bluetooth.observer

      - name: Build Rail samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s sample.rail.simple_txrx -T samples -v --inline-logs

      - name: Build Wifi samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s sample.net.wifi -p siwx917_rb4338a -v --inline-logs -K
