name: Silabs upstream daily build

on:
  schedule:
    - cron: "15 5 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-silabs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-silabs
          toolchains: arm-zephyr-eabi

      - name: Update manifest to point at upstream main branch
        working-directory: zephyr-silabs
        shell: bash
        run: |
          Z_REV=`grep -A 2 'name: zephyr$' west.yml|grep revision:|sed 's/^.*revision: //'`
          sed s/$Z_REV/main/ west.yml > west.yml.new
          mv west.yml.new west.yml
          west update

      - name: Fetch blobs
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west blobs fetch hal_silabs

      - name: Build Entropy test
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s drivers.entropy -p siwx917_rb4338a -v --inline-logs -K

      - name: Build Bluetooth samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s sample.bluetooth.peripheral_hr -p xg27_dk2602a -v --inline-logs -K
          west twister -s sample.bluetooth.peripheral_hr -p siwx917_rb4338a -v --inline-logs -K

      - name: Build Rail samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s sample.rail.simple_txrx -T samples -v --inline-logs

      - name: Build Wifi samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -s sample.net.wifi -p siwx917_rb4338a -v --inline-logs -K
