name: Silabs upstream daily build

on:
  schedule:
    - cron: "15 5 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zephyr-silabs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Silabs-specific python dependencies
        run: |
          pip3 install crc

      - name: Update manifest to point at upstream main branch
        working-directory: zephyr-silabs
        shell: bash
        run: |
          yq -i '(.manifest.projects[] | select(.name == "zephyr") | .revision) = "main"' west.yml

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-silabs
          toolchains: arm-zephyr-eabi

      - name: Fetch blobs
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west blobs fetch hal_silabs

      - name: Build Entropy test
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -s drivers.entropy \
            -p siwx917_rb4338a

      - name: Build Flash test
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs \
            -s drivers.flash.common.default \
            -p siwx917_rb4338a \
            -x DTC_OVERLAY_FILE=$(pwd)/tests/drivers/flash/common/boards/siwx917_rb4338a.overlay

      - name: Build DMA test
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs \
            -s drivers.dma.chan_blen_transfer \
            -p siwx917_rb4338a \
            -x DTC_OVERLAY_FILE=$(pwd)/tests/drivers/dma/chan_blen_transfer/boards/siwx917_rb4338a.overlay \
            -x EXTRA_CONF_FILE=$(pwd)/tests/drivers/dma/chan_blen_transfer/boards/siwx917_rb4338a.conf

      - name: Build Bluetooth samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -s sample.bluetooth.peripheral_hr \
            -s sample.bluetooth.observer \
            -p xg27_dk2602a \
            -p siwx917_rb4338a

      - name: Build Rail samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs \
            -s sample.rail.simple_txrx -T samples

      - name: Build Wifi samples
        working-directory: zephyr-silabs
        shell: bash
        run: |
          west twister -v --inline-logs -K \
            -s sample.net.wifi \
            -p siwx917_rb4338a
          west twister -v --inline-logs -K \
            -s sample.net.wifi \
            -p siwx917_rb4338a \
            -x EXTRA_CONF_FILE=$(pwd)/samples/net/wifi/shell/soc/siwx917_offloaded_sockets.conf
